config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :about, only: [:index]

  resources :contracts, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  resources :tickets, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  resources :qas, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  

  namespace :admin do
    root to: 'dashboard#show'

    resources :categories, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :products, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :service_level_agreements, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :ticket_priorities, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :ticket_status_codes, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :ticket_types, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :user_types, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :qa_categories, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :qas, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :code, presence: true
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  has_many :contract_products
  belongs_to :user
  belongs_to :service_level_agreement

end

app/models/contract_product.rb
class ContractProduct < ActiveRecord::Base
  belongs_to :contract
  belongs_to :product
  has_many :tickets
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user

  validates :description, presence: true

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :contract_products

  validates :code, presence: true
end

app/models/qa.rb
class Qa < ActiveRecord::Base
  belongs_to :qa_category

  validates :problem, presence: true
  validates :solution, presence: true
end

app/models/qa_category.rb
class QaCategory < ActiveRecord::Base
  has_many :qas

  validates :code, presence: true
end

app/models/stat_technician.rb
class StatTechnician < ActiveRecord::Base
end

app/models/stat_ticket.rb
class StatTicket < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  self.per_page = 5
  belongs_to :ticket_priority
  belongs_to :ticket_status_code
  belongs_to :ticket_type
  belongs_to :user
  belongs_to :contract_product
  has_many :notes

  validates :problem_description, presence: true
end

app/models/ticket_priority.rb
class TicketPriority < ActiveRecord::Base
  has_many :tickets

  validates :code, presence: true
end

app/models/ticket_status_code.rb
class TicketStatusCode < ActiveRecord::Base
  has_many :tickets

  validates :code, presence: true
end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base
  has_many :tickets

  validates :code, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :user_type
  has_many :tickets

  has_secure_password

  validates :name, presence: true
  validates :email, presence: true , uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  validates :mobile, presence: true
  validates :mobile, length: {is: 10}

  #, confirmation: { case_sensitive: true }
  #validates :password_confirmation, presence: true, length: { minimum: 6 }

  def self.authenticate_with_credentials(email, password)
    user = User.find_by_email(email.strip.downcase)

    if user && user.authenticate(password)
      user
    else
      nil
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :mobile, :email, :user_type_id, :password, :password_confirmation )
  end

end

app/models/user_notification.rb
class UserNotification < ActiveRecord::Base
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  has_many :users

  validates :code, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/qas_controller.rb
module Admin
  class QasController < ApplicationController
    #require authorization
    before_filter :authorize

    def index
      @qas = Qa.all.order(created_at: :desc)
    end

    def new
      @qa = Qa.new
      @qa_categories = QaCategory.all.order(created_at: :desc)
    end

    def create
      @qa = Qa.new(qa_params)
  
      if @qa.save
        redirect_to [:admin, :qas], notice: 'Q&A created!'
      else
        render :new
      end
    end

    def show
      @qa = Qa.find params[:id]
    end

    def edit
      @qa = Qa.find params[:id]
      @qa_categories = QaCategory.all  
    end
  
    def update
      @qa = Qa.find(params[:id])
      if @qa.update(qa_params)
        redirect_to [:admin, :qas], notice: "QA Updated"
      else
        render :edit
      end
    end
  
    def destroy
      @qa = Qa.find params[:id]
      @qa.destroy
      redirect_to [:admin, :qas], notice: 'QA deleted!'
    end
  
    private
    def qa_params
      params.require(:qa).permit(
        :qa_category_id,
        :problem,
        :solution
      )
    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all.order(created_at: :desc)
  end

  def show
    @note = Note.find params[:id]
  end

end

app/controllers/qas_controller.rb
class QasController < ApplicationController
  def index
    @qas = Qa.all.order(created_at: :desc)
  end

  def show
    @qa = Qa.find params[:id]
  end

  def edit
    @qa = Qa.find params[:id]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include TwilioControls   # sms module

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    # store all emails in lowercase to avoid duplicates and case-sensitive login errors:
    @user.email.downcase!
    @user.user_type_id = UserType.find_by_code('User').id
    
    if @user.save

      begin  #if the mobile # is not registered (free) we will get an error
        #send mail for new user
        UserMailer.welcome_email(@user).deliver_now
        flash.now[:success] = "Email has been sent"

        # send sms
        send_sms(@user.mobile, "Welcome to helpdesk #{@user.name}")
      rescue
        #do nothing
      else
        #do nothing
      ensure
        #do nothing
      end

      # If user saves in the db successfully:
      #flash[:notice] = "Account created successfully!"
      #redirect_to root_path
      session[:user_id] = @user.id

      redirect_to [:tickets], notice: 'Account created Successfully!'
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

private

  def user_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.require(:user).permit(:name, :mobile, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/qas/_qa.html.erb
<tr>
  <td>
  <%= QaCategory.find_by_id(qa.qa_category_id).code %>
  </td>
  <td>
  <%= qa.problem.html_safe %>
  </td>
  <td>
  <%= qa.solution.html_safe %>
  </td>
  <td>
    <%= link_to fa_icon('edit'), edit_admin_qa_path(qa), class: 'btn btn-sm btn-primary' %>
  </td>
  <td>
    <%= link_to fa_icon('trash'), [:admin, qa], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
  </td>

</tr>

app/views/admin/qas/edit.html.erb
<section class="ticket-new">

  <header class="page-header">
    <h1>Edit QA</h1>
  </header>

  <div class="well">
    <%= link_to 'All QAs', [:admin, :qas], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @qa] do |form| %>
    
        <% if form.object.errors.any? %>
         <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">

          <div class="new_ticket-selector col-2">
          <%= form.label :qa_category_id %>
          <% options = options_from_collection_for_select(@qa_categories, 'id', 'code', @qa.qa_category_id) %>
          <%= form.select :qa_category_id,  options, {}, { class: 'form-control' } %>
         <!-- <div></div> -->
          </div>

          <div class="new_ticket-text-area">
          <%= form.label :problem %>
          <%= form.text_area :problem, :class => "tinymce", :rows => 15, :cols => 120 %>
          <%= tinymce %>
          </div>

          <div class="new_ticket-text-area">
          <%= form.label :solution %>
          <%= form.text_area :solution, :class => "tinymce", :rows => 15, :cols => 120 %>
          <%= tinymce %>
          </div>

        </div>

        <%= form.submit 'Update QA', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/admin/qas/index.html.erb
<section class="admin-qa-index">

  <header class="page-header">
    <h1>Admin &raquo; QA</h1>
  </header>

  <div class="well">
    <%= link_to '+ New QA', [:new, :admin, :qa], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default qas">

    <table class="table table-bordered">
      <thead class="table_head">
        <tr>
          <th>QA Category</th>
          <th>Problem</th>
          <th>Solution</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if @qas %>
          <%= render @qas %>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/admin/qas/new.html.erb
<section class="admin-qa-new">

  <header class="page-header">
    <h1>Admin &raquo; New QA</h1>
  </header>

  <div class="well">
    <%= link_to 'All QAs', [:admin, :qas], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @qa] do |form| %>
    
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">

          <div class="new_ticket-selector col-2">
         <%= form.label :qa_category_id %>
          <% options = options_from_collection_for_select(@qa_categories, 'id', 'code') %>
          <%= form.select :qa_category_id,  options, {}, { class: 'form-control' } %>
          <!--<div></div>-->
          </div>
          <div class="new_ticket-text-area">
            <%= form.label :problem %>
            <%= form.text_area :problem, :class => "tinymce", :rows => 15, :cols => 120 %>
            <%= tinymce %>
          </div>

          <div class="new_ticket-text-area">
            <%= form.label :solution %>
            <%= form.text_area :solution, :class => "tinymce", :rows => 15, :cols => 120 %>
            <%= tinymce %>
          </div>
        </div>

        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/qas/_qa.html.erb
<tr>

  <td  width="20%">
    <%= QaCategory.find(qa.qa_category_id).code %>
  </td>

  <td  width="70%">
    <%= qa.problem.html_safe %>
  </td>

  <td  width="10%">
    <%= link_to fa_icon('edit'), edit_qa_path(qa), class: 'btn btn-sm btn-primary' %>
  </td>

</tr>

app/views/qas/edit.html.erb
<section class="ticket-new">

  <header class="page-header">
    <h1>F.A.Q</h1>
  </header>

  <div class="well">
    <%= link_to 'All F.A.Qs', [:qas], class: 'btn btn-info' %>
  </div>

  <div class="row">

        <div class="form-group">

          <h3> Problem </h3>
          <%= @qa.problem.html_safe %>
          <hr />
          <h3> Solution </h3>
          <%= @qa.solution.html_safe %>
          <hr />

        </div>
  </div>

</section>

app/views/qas/index.html.erb
<section class="admin-qa-index">

  <header class="page-header">
    <h1>F.A.Q</h1>
  </header>

  <!--<div class="well">
    <h3> F.A.Q </h3>
  </div> -->

  <div class="panel panel-default qas">

    <table class="table table-bordered">
      <thead class="table_head">
        <tr>
          <th width="20%";>QA Category</th>
          <th width="70%";>Problem</th>
          <th width="10%";></th>
        </tr>
      </thead>
      <tbody>
        <% if @qas %>
          <%= render @qas %>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/qas/new.html.erb
<section class="admin-qa-new">

  <header class="page-header">
    <h1>Admin &raquo; New QA</h1>
  </header>

  <div class="well">
    <%= link_to 'All QAs', [:admin, :qas], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @qa] do |form| %>
    
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :qa_category_id %>
          <%= form.text_field :qa_category_id, class: 'form-control' %>

          <%= form.label :problem %>
          <%= form.text_area :problem, :class => "tinymce", :rows => 15, :cols => 120 %>
          <%= tinymce %>

          <%= form.label :solution %>
          <%= form.text_area :solution, :class => "tinymce", :rows => 15, :cols => 120 %>
          <%= tinymce %>

        </div>
        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>