config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :about, only: [:index]

  resources :contracts, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  resources :tickets, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  resources :qas, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  

  namespace :admin do
    root to: 'dashboard#show'

    resources :categories, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :products, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :service_level_agreements, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :ticket_priorities, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :ticket_status_codes, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :ticket_types, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :user_types, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :qa_categories, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :qas, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :code, presence: true
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  has_many :contract_products
  belongs_to :user
  belongs_to :service_level_agreement

end

app/models/contract_product.rb
class ContractProduct < ActiveRecord::Base
  belongs_to :contract
  belongs_to :product
  has_many :tickets
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user

  validates :description, presence: true

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :contract_products

  validates :code, presence: true
end

app/models/qa.rb
class Qa < ActiveRecord::Base
  belongs_to :qa_category

  validates :problem, presence: true
  validates :solution, presence: true
end

app/models/qa_category.rb
class QaCategory < ActiveRecord::Base
  has_many :qas

  validates :code, presence: true
end

app/models/stat_technician.rb
class StatTechnician < ActiveRecord::Base
end

app/models/stat_ticket.rb
class StatTicket < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  self.per_page = 5
  belongs_to :ticket_priority
  belongs_to :ticket_status_code
  belongs_to :ticket_type
  belongs_to :user
  belongs_to :contract_product
  has_many :notes

  validates :problem_description, presence: true
end

app/models/ticket_priority.rb
class TicketPriority < ActiveRecord::Base
  has_many :tickets

  validates :code, presence: true
end

app/models/ticket_status_code.rb
class TicketStatusCode < ActiveRecord::Base
  has_many :tickets

  validates :code, presence: true
end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base
  has_many :tickets

  validates :code, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :user_type
  has_many :tickets

  has_secure_password

  validates :name, presence: true
  validates :email, presence: true , uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  validates :mobile, presence: true
  validates :mobile, length: {is: 10}

  #, confirmation: { case_sensitive: true }
  #validates :password_confirmation, presence: true, length: { minimum: 6 }

  def self.authenticate_with_credentials(email, password)
    user = User.find_by_email(email.strip.downcase)

    if user && user.authenticate(password)
      user
    else
      nil
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :mobile, :email, :user_type_id, :password, :password_confirmation )
  end

end

app/models/user_notification.rb
class UserNotification < ActiveRecord::Base
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  has_many :users

  validates :code, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    #require authorization
    before_filter :authorize

    def index
      @products = Product.all.order(created_at: :desc)
    end

    def new
      @product = Product.new
      @categories = Category.all
    end
  
    def create
      @product = Product.new(product_params)
  
      if @product.save
        redirect_to [:admin, :products], notice: 'Product created!'
      else
        render :new
      end
    end
  
    def show
      @product = Product.find params[:id]
    end

    def edit
      @product = Product.find params[:id]
      @categories = Category.all
    end
  
    def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        redirect_to [:admin, :products], notice: "Product Updated"
      else
        render :edit
      end
    end
  
    def destroy
      @product = Product.find params[:id]
      @product.destroy
      redirect_to [:admin, :products], notice: 'Product deleted!'
    end
  

    private
    def product_params
      params.require(:product).permit(
        :category_id,
        :code,
        :description,
        :model
      )
    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all.order(created_at: :desc)
  end

  def show
    @note = Note.find params[:id]
  end

end

app/controllers/qas_controller.rb
class QasController < ApplicationController
  def index
    @qas = Qa.all.order(created_at: :desc)
  end

  def show
    @qa = Qa.find params[:id]
  end

  def edit
    @qa = Qa.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/products/_product.html.erb
<tr>
  <td>
  <%= Category.find_by_id(product.category_id).code %>
  </td>
  <td>
  <%= product.code %>
  </td>
  <td>
  <%= product.description.html_safe %>
  </td>
  <td>
  <%= product.model %>
  </td>
  <td>
    <%= link_to fa_icon('edit'), edit_admin_product_path(product), class: 'btn btn-sm btn-primary' %>
  </td>
  <td>
    <%= link_to fa_icon('trash'), [:admin, product], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
  </td>

</tr>

app/views/admin/products/edit.html.erb
<section class="ticket-new">

  <header class="page-header">
    <h1>Edit Product</h1>
  </header>

  <div class="well">
    <%= link_to 'All Products', [:admin, :products], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @product] do |form| %>
    
        <% if form.object.errors.any? %>
         <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">

          <div class="new_ticket-selector col-2">
          <%= form.label :category_id %>
          <% options = options_from_collection_for_select(@categories, 'id', 'code', @product.category_id) %>
          <%= form.select :category_id,  options, {}, { class: 'form-control' } %>
          <div></div>
          </div>

          <div class="form-selector">
          <%= form.label :code %>
          <%= form.text_field :code, class: 'form-control' %>
          </div>
         
          <%= form.label :model %>
          <%= form.text_field :model, class: 'form-control' %>

          <div class="new_ticket-text-area">
            <%= form.label :description %>
            <%= form.text_area :description, :class => "tinymce", :rows => 15, :cols => 120 %>
            <%= tinymce %>
            </div>


        </div>

        <%= form.submit 'Update Product', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/admin/products/index.html.erb
<section class="admin-product-index">

  <header class="page-header">
    <h1>Admin &raquo; Products</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Product', [:new, :admin, :product], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default qas">

    <table class="table table-bordered">
      <thead class="table_head">
        <tr>
          <th>Category</th>
          <th>Code</th>
          <th>Description</th>
          <th>Model</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% if @products %>
        <%= render @products %>
      <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/admin/products/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Admin &raquo; New Product</h1>
  </header>

  <div class="well">
    <%= link_to 'All Products', [:admin, :products], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">

      <%= form_for [:admin, @product] do |form| %>

        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">

          <div class="new_ticket-selector col-2">
          <%= form.label :category_id %>
          <% options = options_from_collection_for_select(@categories, 'id', 'code') %>
          <%= form.select :category_id,  options, {}, { class: 'form-control' } %>
          <!--<div></div>-->
          </div>

          <div class="form-selector">
          <%= form.label :code %>
          <%= form.text_field :code, class: 'form-control' %>
          </div>
          
          <%= form.label :model %>
          <%= form.text_field :model, class: 'form-control' %>
          
          <div class="new_ticket-text-area">
            <%= form.label :description %>
            <%= form.text_area :description, :class => "tinymce", :rows => 15, :cols => 120 %>
            <%= tinymce %>
          </div>
        </div>

        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/admin/products/show.html.erb
<section class="products-show">

  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @product.image.url, class: 'main-img' %>
        <%= link_to 'Back', products_path %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Category</dt>
          <dd><%= @product.Category_id %></dd>
          <dt>Code</dt>
          <dd><%= @product.code %></dd>
          <dt>Description</dt>
          <dd><%= @product.description %></dd>
          <dt>Model</dt>
          <dd><%= @product.model %></dd>
        </dl>
      </div>
    </div>

  </article>

</section>