config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :about, only: [:index]

  resources :contracts, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  resources :tickets, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  resources :qas, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  

  namespace :admin do
    root to: 'dashboard#show'

    resources :categories, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :products, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :service_level_agreements, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :ticket_priorities, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :ticket_status_codes, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :ticket_types, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :user_types, only: [:index, :show, :new, :edit, :update, :create, :destroy]

    resources :qa_categories, only: [:index, :show, :new, :edit, :update, :create, :destroy]
    resources :qas, only: [:index, :show, :new, :edit, :update, :create, :destroy]
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :code, presence: true
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  has_many :contract_products
  belongs_to :user
  belongs_to :service_level_agreement

end

app/models/contract_product.rb
class ContractProduct < ActiveRecord::Base
  belongs_to :contract
  belongs_to :product
  has_many :tickets
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user

  validates :description, presence: true

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :contract_products

  validates :code, presence: true
end

app/models/qa.rb
class Qa < ActiveRecord::Base
  belongs_to :qa_category

  validates :problem, presence: true
  validates :solution, presence: true
end

app/models/qa_category.rb
class QaCategory < ActiveRecord::Base
  has_many :qas

  validates :code, presence: true
end

app/models/stat_technician.rb
class StatTechnician < ActiveRecord::Base
end

app/models/stat_ticket.rb
class StatTicket < ActiveRecord::Base
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  self.per_page = 5
  belongs_to :ticket_priority
  belongs_to :ticket_status_code
  belongs_to :ticket_type
  belongs_to :user
  belongs_to :contract_product
  has_many :notes

  validates :problem_description, presence: true
end

app/models/ticket_priority.rb
class TicketPriority < ActiveRecord::Base
  has_many :tickets

  validates :code, presence: true
end

app/models/ticket_status_code.rb
class TicketStatusCode < ActiveRecord::Base
  has_many :tickets

  validates :code, presence: true
end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base
  has_many :tickets

  validates :code, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :user_type
  has_many :tickets

  has_secure_password

  validates :name, presence: true
  validates :email, presence: true , uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  validates :mobile, presence: true
  validates :mobile, length: {is: 10}

  #, confirmation: { case_sensitive: true }
  #validates :password_confirmation, presence: true, length: { minimum: 6 }

  def self.authenticate_with_credentials(email, password)
    user = User.find_by_email(email.strip.downcase)

    if user && user.authenticate(password)
      user
    else
      nil
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :mobile, :email, :user_type_id, :password, :password_confirmation )
  end

end

app/models/user_notification.rb
class UserNotification < ActiveRecord::Base
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  has_many :users

  validates :code, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin/ticket_priorities_controller.rb
module Admin
  class TicketPrioritiesController < ApplicationController
    #require authorization
    before_filter :authorize


    def index
      @ticket_priorities = TicketPriority.all.order(created_at: :desc)
    end

    def new
      @ticket_priority = TicketPriority.new
    end
  
    def create
      @ticket_priority = TicketPriority.new(ticket_priority_params)
  
      if @ticket_priority.save
        redirect_to [:admin, :ticket_priorities], notice: 'Ticket Priority created!'
      else
        render :new
      end
    end

    def show
      @ticket_priority = TicketPriority.find params[:id]
    end

    def edit
      @ticket_priority = TicketPriority.find params[:id]
    end
  
    def update
      @ticket_priority = TicketPriority.find(params[:id])
      if @ticket_priority.update(ticket_priority_params)
        redirect_to [:admin, :ticket_priorities], notice: "Ticket Priority Updated"
      else
        render :edit
      end
    end
  
    def destroy
      @ticket_priority = TicketPriority.find params[:id]
      @ticket_priority.destroy
      redirect_to [:admin, :ticket_priorities], notice: 'Ticket Priority deleted!'
    end
  
    private
    def ticket_priority_params
      params.require(:ticket_priority).permit(
        :code,
        :description,
        :business_days,
        :business_hours
      )
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all.order(created_at: :desc)
  end

  def show
    @note = Note.find params[:id]
  end

end

app/controllers/qas_controller.rb
class QasController < ApplicationController
  def index
    @qas = Qa.all.order(created_at: :desc)
  end

  def show
    @qa = Qa.find params[:id]
  end

  def edit
    @qa = Qa.find params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/ticket_priorities/_ticket_priority.html.erb
<tr>
  <td>
    <%= ticket_priority.code %>
  </td>
  <td>
    <%= ticket_priority.description.html_safe %>
  </td>
  <td>
    <%= ticket_priority.business_days %>
  </td>
  <td>
    <%= ticket_priority.business_hours %>
  </td>
  <td>
    <%= link_to fa_icon('edit'), edit_admin_ticket_priority_path(ticket_priority), class: 'btn btn-sm btn-primary' %>
  </td>
  <td>
    <%= link_to fa_icon('trash'), [:admin, ticket_priority], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
  </td>

</tr>

app/views/admin/ticket_priorities/edit.html.erb
<section class="ticket-new">

  <header class="page-header">
    <h1>Edit Ticket Priority</h1>
  </header>

  <div class="well">
    <%= link_to 'All Ticket Priorities', [:admin, :ticket_priorities], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @ticket_priority] do |form| %>
    
        <% if form.object.errors.any? %>
         <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :code %>
          <%= form.text_field :code, class: 'form-control' %>

          <%= form.label :description %>
          <div class="new_ticket-text-area">
          <%= form.text_area :description, :class => "tinymce", :rows => 15, :cols => 120 %>
          <%= tinymce %>
          </div>

          <%= form.label :business_days %>
          <%= form.text_field :business_days, class: 'form-control' %>

          <%= form.label :business_hours %>
          <%= form.text_field :business_hours, class: 'form-control' %>
        </div>

        <%= form.submit 'Update Ticket Priority', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>

app/views/admin/ticket_priorities/index.html.erb
<section class="admin-ticket_priorities-index">

  <header class="page-header">
    <h1>Admin &raquo; Ticket Priorities</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Priority', [:new, :admin, :ticket_priority], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default ticket_priorities">

    <table class="table table-bordered">
      <thead class="table_head">
        <tr>
          <th>Priority</th>
          <th>Description</th>
          <th>Business Days</th>
          <th>Business Hours</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      <% if @ticket_priorities %>
        <%= render @ticket_priorities %>
      <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/admin/ticket_priorities/new.html.erb
<section class="admin-ticket_priorities-new">

  <header class="page-header">
    <h1>Admin &raquo; New Priority</h1>
  </header>

  <div class="well">
    <%= link_to 'All Ticket Priorities', [:admin, :ticket_priorities], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @ticket_priority] do |form| %>
    
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :code %>
          <%= form.text_field :code, class: 'form-control' %>

          <%= form.label :description %>
          <div class="new_ticket-text-area">
            <%= form.text_area :description, :class => "tinymce", :rows => 15, :cols => 120 %>
            <%= tinymce %>
          </div>

          <%= form.label :business_days %>
          <%= form.number_field :business_days, class: 'form-control' %>

          <%= form.label :business_hours %>
          <%= form.number_field :business_hours, class: 'form-control' %>
        </div>

        <%= form.submit 'Create Priority', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>